import os

UPSTOX_ACCESS_TOKEN=os.getenv("UPSTOX_ACCESS_TOKEN","")
TELEGRAM_BOT_TOKEN=os.getenv("TELEGRAM_BOT_TOKEN","")
TELEGRAM_CHAT_ID=os.getenv("TELEGRAM_CHAT_ID","")

MIN_PRICE=20.0
MIN_TURNOVER_CR=30.0
MIN_SWING_RETURN=30.0
MAX_FROM_52W_HIGH=20.0
MIN_ATR_PCT=3.9
MIN_RVOL=1.30
BREAKOUT_BUFFER_PCT=0.50
CANDIDATE_SCORE_REQUIRED=4
CANDIDATE_NEAR_HIGH_PCT=15.0
CANDIDATE_MIN_SWING=20.0

VCP_SEGMENT=5
VCP_BASE_LEN=30
VCP_RANGE_SHRINK=0.80
VCP_VOLUME_RATIO=0.80
VCP_ATR_RATIO=0.80
VCP_MAX_TIGHTNESS=8.0
VCP_UPPER_BASE_RATIO=0.65
VCP_MIN_QUALITY_SCORE=4

MAX_UNIVERSE=1500
